RentalQuotationEnqiry/Controllers/QuotationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Newtonsoft.Json;
using RentalQuotation.Model;
using RentalQuotation.Repository.Interface;
using RentalQuotationEnqiry.Models;

namespace RentalQuotationEnqiry.Controllers
{
    public class QuotationController : Controller
    {

        private readonly IQuotationData _quotationData;
        private readonly ICostComponent _costCompData;

        public QuotationController(IQuotationData quotationData, ICostComponent costCompData)
        {
            _quotationData = quotationData;
            _costCompData = costCompData;
        }
        [LoginAttribute]
        public ActionResult Index()
        {
            string val = Session["Login"].ToString();
            User u = JsonConvert.DeserializeObject<User>(val);
            ViewBag.AdminUser = 0;
            if (u.Role.RoleName.ToUpper()=="ADMIN")
            {
                ViewBag.AdminUser = 1;
            }
            var quotations = _quotationData.GetAll().ToList();
            return View(quotations);
        }



        [HttpPost]
        public JsonResult AddRemarks(QuotationList modelData)
        {
            try
            {
                var dat = _quotationData.Update(modelData);
                return Json(new { result = true }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(new { result = false, error = ex.Message }, JsonRequestBehavior.AllowGet);
            }
        }

        [LoginAttribute]
        public ActionResult CreateNewQuotation()
        {
            return View();
        }

        [HttpPost]
        public JsonResult CreateQuotation(QuotationList modelData)
        {
            try
            {
                var dat = _quotationData.Insert(modelData);
                return Json(new { result = true }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {

                return Json(new { result = false, error = ex.Message }, JsonRequestBehavior.AllowGet);
            }
        }

        [LoginAttribute]
        public ActionResult AddNewCostComponent()
        {
            return View();
        }

        [HttpPost]
        public JsonResult CreateCostComponent(QuotationDetail modelData)
        {
            try
            {
                var dat = _costCompData.Insert(modelData);
                return Json(new { result = true }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {

                return Json(new { result = false, error = ex.Message }, JsonRequestBehavior.AllowGet);
            }
        }
    }
}

RentalQuotationEnqiry/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Rental Quotation Enquiry </title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/moment.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/bootstrap-datetimepicker.min.js"></script>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-datetimepicker.min.css" rel="stylesheet" />
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Quotation List", "Index", "Quotation", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Create Quotation", "CreateNewQuotation", "Quotation")</li>
                    <li>@Html.ActionLink("Menu", "Index", "Menu")</li>
                    <li>@Html.ActionLink("Role", "Index", "Role")</li>
                    <li>@Html.ActionLink("User", "Index", "User")</li>
                </ul>

                <ul class="nav navbar-nav navbar-right">
                        <li>@Html.ActionLink("Log off", "LogOut", "User", routeValues: null, htmlAttributes: new { id = "loginLink" })</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

</body>
</html>